[package]
name = "simple_db"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
clap = { version = "4.5.39", features = ["derive"] }
rustyline = "16.0.0"
rustyline-derive = "0.11.1"
serde_json = "1.0.140"
sqlparser = "0.56"
tempfile = "3.20.0"
thiserror = "2.0.12"
